### ISSUE TITLE
Feature selection at boot time (replacing runtime dynamic feature:install)

### ISSUE THREAD

**Issue by shague** [vorburger/opendaylight-simple#30]
The CSIT sometimes pre-configures the features using featuresBoot or at runtime via the feature:install.

**Comment by vorburger** [comment]
`feature:install` will never be supported in opendaylight-simple ... :smiling_imp: 

Close this issue, or keep it open as a reminder to discuss this futher by voice, some time?

**Comment by shague** [comment]
Is there an equivalent? genius starts different features than netvirt so we need a way to do the same.

**Comment by vorburger** [comment]
In the short term, this project will only provide (first) a genius distribution and (then) a netvirt one.

In the medium term, this project will enable other projects than genius & netvirt to create simple distributions of a fixed set of projects at build time.

In the long term, as per [this slide of the presentation given in 2018.09 at the ODL DDF during ONS Europe in Amsterdam](https://docs.google.com/presentation/d/14TM9oCn0nLo7RJAhAHglXM4P6oTxsVjJBfFE1wl1qJc/edit#slide=id.g422c37256b_0_84), this project may allow dynamic feature selection, but it it just would be at boot time instead of at runtime.

This project (opendaylight-simple) will **_NEVER_** have Karaf OSGi like full hot dynamic runtime features à la `feature:install`. That's kind of one the its main points... :smile:

**Comment by shague** [comment]
Ok, in the short-term we will have two distributions - one genius and second netvirt. The csit deployment tool will need to be updated to take a distinct distro url to download and install.

**Comment by tnevrekar** [comment]
Not moving this to upstream as we can in stead have different packages for netvirt, genius
